gitlab_runner_shell:
  build: gitlab-runner
  command: run
  container_name: gitlab-runner-shell
  env_file:
    - gitlab_runner.env
  environment:
    CI_SERVER_URL: http://gitlab.example.com/ci
    RUNNER_EXECUTOR: shell
    RUNNER_SHELL: bash
    RUNNER_TAG_LIST: shell
  external_links:
    - gitlab:gitlab.example.com
    - gitlab-registry:registry
  hostname: runner-shell
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - gitlab_runner_shell_data
    
gitlab_runner_shell_data:
  image: alpine
  command: /bin/true
  container_name: gitlab-runner-shell-data
  volumes:
    - /etc/gitlab-runner
